---
external-dns:
  policy: sync
  sources: ["ingress", "service"]
  provider: cloudflare
  domainFilters: ["lpsm.cloud"]
  extraArgs:
    - --cloudflare-proxied
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret-properties
          key: cloudflare_api_token
    - name: CF_API_EMAIL
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret-properties
          key: cloudflare_email
