---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret-properties
  annotations:
    replicator.v1.mittwald.de/replicate-to: "argocd,demo,origin-ca-issuer"
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secrets-accessor
  target:
    name: cloudflare-secret-properties
    creationPolicy: Owner
  data:
    - secretKey: origin-key
      remoteRef:
        key: id:0f4f8ceb-ab47-46cb-9a66-93a43b01be2f
        version: latest_enabled
