---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret-properties
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secrets-accessor
  target:
    name: cloudflare-secret-properties
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: id:7d7c1a6c-da3e-421f-a2ae-1ccd6a7426a7
        version: latest_enabled
