---
helmDefaults:
  kubeContext: scalaway-personal-pocs-services-001
---
repositories:
- name: argo-cd
  url: https://argoproj.github.io/argo-helm
---
releases:
# Setup External Secrets - Cluster Secret Store
- name: cluster-secret-store
  namespace: external-secrets
  chart: ./2-system/cluster-secret-store
# Setup Cert-Manager - Cluster Issuer + Certificate
- name: cluster-issuers
  namespace: cert-manager
  chart: ./2-system/cluster-issuers
# Setup ArgoCD
- name: argocd
  namespace: argocd
  chart: ./1-bootstrap/argocd
