---
helmDefaults:
  kubeContext: scalaway-personal-pocs-services-001
---
repositories:
- name: cert-manager
  url: https://charts.jetstack.io
- name: external-secrets
  url: https://charts.external-secrets.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
---
releases:
# Setup Network
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ./2-system/network/ingress-nginx
# Setup External Secrets
- name: external-secrets
  namespace: external-secrets
  chart: ./2-system/security/external-secrets
# Setup Certificates
- name: cert-manager
  namespace: cert-manager
  chart: ./2-system/network/cert-manager
