---
echo-server:
  replicaCount: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: echo-server.lpsm.cloud
        paths:
          - /
    tls:
      - hosts:
          - echo-server.lpsm.cloud
        secretName: echo-server-tls
