---
echo-server:
  replicaCount: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/issuer: production-issuer
      cert-manager.io/issuer-kind: OriginIssuer
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
      external-dns.beta.kubernetes.io/hostname: echo-server.lpsm.dev
      external-dns.beta.kubernetes.io/ttl: "120"
    hosts:
      - host: echo-server.lpsm.dev
        paths:
          - /
    tls:
      - hosts:
          - echo-server.lpsm.dev
        secretName: echo-tls
