---
formatter: markdown table

sections:
  show:
  - footer
  - header
  - requirements
  - providers
  - modules
  - resources
  - inputs
  - outputs

sort:
  enabled: true
  by: required

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
