---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: scaleway-secrets-accessor
spec:
  provider:
    scaleway:
      region: {{ .Values.scaleway.region }}
      projectId: {{ .Values.scaleway.projectId }}
      accessKey:
        secretRef:
          name: scaleway-secrets-accessor
          namespace: default
          key: access-key
      secretKey:
        secretRef:
          name: scaleway-secrets-accessor
          namespace: default
          key: secret-access-key
