---
{{- if .Values.gcp.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secrets-accessor
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secrets-accessor
            namespace: default
            key: secret-access-credentials
{{- end -}}
