apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lpsm-cloud
spec:
  secretName: lpsm-cloud-tls
  dnsNames:
  - "*.lpsm.cloud"
  - "lpsm.cloud"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
---
