---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace : cert-manager
spec:
  acme:
    email: lpsm-dev@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          cloudflare:
            email: {{ .Values.cloudflare.email }}
            apiTokenSecretRef:
              name: cloudflare-secret-properties
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace : cert-manager
spec:
  acme:
    email: lpsm-dev@protonmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          cloudflare:
            email: {{ .Values.cloudflare.email }}
            apiTokenSecretRef:
              name: cloudflare-secret-properties
              key: api-token
