#!/bin/bash
set -x

kubectl kc list scalaway-personal-pocs-services-001 >/dev/null 2>&1
if [ "$?" -ne 0 ]; then
  # kubeconfig don't exists. add kubeconfig
  kubectl kc add -f $(pwd)/kubeconfig --context-name scalaway-personal-pocs-services-001 -c
else
  # kubeconfig exists. removing it and adding a new one
  kubectl kc delete scalaway-personal-pocs-services-001 >/dev/null 2>&1
  kubectl kc add -f $(pwd)/kubeconfig --context-name scalaway-personal-pocs-services-001 -c
fi
