---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret-properties
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secrets-accessor
  target:
    name: cloudflare-secret-properties
    creationPolicy: Owner
  data:
    - secretKey: origin-key
      remoteRef:
        key: id:b6c9d23d-5ab3-408d-8d9b-c1faba6dc5a9
        version: latest_enabled
