---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: production-issuer
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: service-key
      key: key
