---
ingress-nginx:
  defaultBackend:
    enabled: true
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi
  controller:
    admissionWebhooks:
      enabled: false
    ingressClassResource:
      default: true
      enabled: true
    kind: DaemonSet
    service:
      type: LoadBalancer
