---
ingress-nginx:
  defaultBackend:
    enabled: false
  controller:
    admissionWebhooks:
      enabled: false
    ingressClassResource:
      default: true
      enabled: true
    kind: DaemonSet
    service:
      type: LoadBalancer
