---
ingress-nginx:
  defaultBackend:
    enabled: false
  controller:
    admissionWebhooks:
      enabled: false
    config:
      client-body-buffer-size: 100M
      client-body-timeout: 120
      client-header-timeout: 120
      enable-brotli: "true"
      enable-real-ip: "true"
      keep-alive-requests: 10000
      keep-alive: 120
      proxy-body-size: 0
      proxy-buffer-size: 16k
      ssl-protocols: TLSv1.3 TLSv1.2
      use-forwarded-headers: true
      use-geoip2: true
    extraArgs:
      default-ssl-certificate: ingress-nginx/lpsm-dev
    ingressClassResource:
      default: true
      enabled: true
    kind: DaemonSet
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: lpsm.dev
