---
services:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    ports:
      - "8282:80/tcp"
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "./db:/var/www/html/db"
      - "./logos:/var/www/html/images/uploads/logos"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - wallosnet

networks:
  wallosnet:
    driver: bridge
